### ISSUE TITLE
RSSAC002 API written in R

### ISSUE THREAD

**Issue by smutt** [rssac-caucus/RSSAC002-data#1]
Consider adding a link or fork to my RSSAC002 API written in R. It's 9 months old and I think it misses at least one root and probably needs some other minor updates. I'm interested to hear if people think it is worth updating or not. I suspect it would be very little work on my part.

https://github.com/smutt/RSSAC002

**Comment by wessels** [comment]
Thanks Andrew, I've updated our README and added a link to your project.

(for now I think RSSAC002-data itself should be limited to only data files, plus a script to fetch them, but I'm open to what others think)

**Comment by smutt** [comment]
Thanks Duane.
